/**
 * Countries participating in the 417 / 462 programs (display list for
 * onboarding — not used for eligibility logic).
 */
export const WHV_COUNTRIES = [
  "Argentina",
  "Austria",
  "Belgium",
  "Brazil",
  "Canada",
  "Chile",
  "China",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Ecuador",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mongolia",
  "Netherlands",
  "Norway",
  "Papua New Guinea",
  "Peru",
  "Poland",
  "Portugal",
  "San Marino",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Vietnam",
  "Other",
] as const;
