/**
 * Visa evidence pack PDF (PRD 1.5) — built with @react-pdf/renderer.
 * Server-side only (imported from the /api/export route).
 */
import {
  Document,
  Image,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";
import type { ChecklistItem } from "./checklist";

const ORANGE = "#ea580c";
const MUTED = "#6b7280";
const BORDER = "#e5e7eb";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#111827" },
  h1: { fontSize: 22, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  h2: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginTop: 18,
    marginBottom: 8,
    color: ORANGE,
  },
  muted: { color: MUTED },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
    paddingVertical: 5,
  },
  headerRow: {
    flexDirection: "row",
    borderBottomWidth: 1.5,
    borderBottomColor: "#111827",
    paddingVertical: 5,
  },
  bold: { fontFamily: "Helvetica-Bold" },
  big: { fontSize: 30, fontFamily: "Helvetica-Bold" },
  badge: { color: ORANGE, fontFamily: "Helvetica-Bold" },
  disclaimer: {
    marginTop: 24,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: BORDER,
    fontSize: 8,
    color: MUTED,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: MUTED,
    textAlign: "center",
  },
  proofImage: {
    marginTop: 10,
    maxHeight: 600,
    objectFit: "contain",
  },
});

export type ExportPeriod = {
  employerName: string;
  postcode: string | null;
  postcodeEligible: boolean | null;
  workType: string;
  industry: string | null;
  startDate: string;
  endDate: string | null;
  days: number;
};

export type ExportDoc = {
  label: string;
  type: string;
  periodLabel: string | null;
  ocrSummary: string | null;
};

export type ExportImage = {
  caption: string;
  data: Buffer;
  format: "jpg" | "png";
};

export type ExportData = {
  fullName: string;
  email: string | null;
  visaLabel: string;
  goalLabel: string;
  arrivalDate: string | null;
  visaExpiry: string | null;
  generatedOn: string;
  totalDays: number;
  requiredDays: number;
  periods: ExportPeriod[];
  checklist: ChecklistItem[];
  documents: ExportDoc[];
  images: ExportImage[];
};

const DISCLAIMER =
  "88Mate is an organisation tool, not migration advice. This pack summarises data you entered and documents you uploaded. Always verify official requirements on immi.homeaffairs.gov.au — eligibility decisions rest with the Department of Home Affairs.";

const CHECK: Record<string, string> = {
  complete: "[x]",
  partial: "[~]",
  missing: "[ ]",
  optional: "[o]",
};

export function buildExportDocument(data: ExportData) {
  return (
    <Document
      title="88Mate — Visa Evidence Pack"
      author="88Mate"
      creator="88Mate"
    >
      {/* Cover + summary */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Visa Evidence Pack</Text>
        <Text style={styles.muted}>
          Generated by 88Mate on {data.generatedOn}
        </Text>

        <View style={{ marginTop: 20 }}>
          <Text style={styles.bold}>{data.fullName}</Text>
          {data.email ? <Text style={styles.muted}>{data.email}</Text> : null}
          <Text style={{ marginTop: 6 }}>{data.visaLabel}</Text>
          <Text>Goal: {data.goalLabel}</Text>
          {data.arrivalDate ? (
            <Text>Arrived in Australia: {data.arrivalDate}</Text>
          ) : null}
          {data.visaExpiry ? (
            <Text>Estimated visa expiry: {data.visaExpiry}</Text>
          ) : null}
        </View>

        <View style={{ marginTop: 28, flexDirection: "row", alignItems: "flex-end" }}>
          <Text style={styles.big}>{data.totalDays}</Text>
          <Text style={{ fontSize: 14, marginLeft: 4, marginBottom: 4 }}>
            / {data.requiredDays} days of specified work
          </Text>
        </View>

        <Text style={styles.h2}>Work periods</Text>
        <View style={styles.headerRow}>
          <Text style={[styles.bold, { width: "26%" }]}>Employer</Text>
          <Text style={[styles.bold, { width: "26%" }]}>Dates</Text>
          <Text style={[styles.bold, { width: "16%" }]}>Type</Text>
          <Text style={[styles.bold, { width: "16%" }]}>Postcode</Text>
          <Text style={[styles.bold, { width: "16%", textAlign: "right" }]}>
            Days
          </Text>
        </View>
        {data.periods.map((p, i) => (
          <View key={i} style={styles.row}>
            <Text style={{ width: "26%" }}>{p.employerName}</Text>
            <Text style={{ width: "26%" }}>
              {p.startDate} → {p.endDate ?? "ongoing"}
            </Text>
            <Text style={{ width: "16%" }}>{p.workType.replace("_", " ")}</Text>
            <Text style={{ width: "16%" }}>
              {p.postcode ?? "—"}
              {p.postcodeEligible === false ? " (!)" : ""}
            </Text>
            <Text style={{ width: "16%", textAlign: "right" }}>{p.days}</Text>
          </View>
        ))}
        {data.periods.some((p) => p.postcodeEligible === false) ? (
          <Text style={{ marginTop: 6, fontSize: 8, color: MUTED }}>
            (!) postcode not on the eligible list for this visa and industry —
            these days may not count.
          </Text>
        ) : null}

        <Text style={styles.h2}>Document checklist</Text>
        {data.checklist.map((item) => (
          <View key={item.key} style={styles.row}>
            <Text style={[styles.badge, { width: "8%" }]}>
              {CHECK[item.status]}
            </Text>
            <Text style={{ width: "62%" }}>{item.label}</Text>
            <Text style={{ width: "30%", textAlign: "right", color: MUTED }}>
              {item.done}/{item.total}
              {item.status === "optional" ? " (recommended)" : ""}
            </Text>
          </View>
        ))}

        <Text style={styles.disclaimer}>{DISCLAIMER}</Text>
        <Text style={styles.footer} fixed>
          88Mate — Visa Evidence Pack
        </Text>
      </Page>

      {/* Documents inventory */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Evidence inventory</Text>
        <Text style={styles.muted}>
          {data.documents.length} document
          {data.documents.length === 1 ? "" : "s"} stored in the 88Mate vault.
          Images are attached on the following pages; PDFs are listed here and
          should be joined separately to your application.
        </Text>

        <View style={[styles.headerRow, { marginTop: 16 }]}>
          <Text style={[styles.bold, { width: "34%" }]}>File</Text>
          <Text style={[styles.bold, { width: "18%" }]}>Type</Text>
          <Text style={[styles.bold, { width: "48%" }]}>Details</Text>
        </View>
        {data.documents.map((d, i) => (
          <View key={i} style={styles.row}>
            <Text style={{ width: "34%" }}>{d.label}</Text>
            <Text style={{ width: "18%" }}>{d.type.replace(/_/g, " ")}</Text>
            <Text style={{ width: "48%" }}>
              {d.periodLabel ? `${d.periodLabel}. ` : ""}
              {d.ocrSummary ?? ""}
            </Text>
          </View>
        ))}

        <Text style={styles.footer} fixed>
          88Mate — Visa Evidence Pack
        </Text>
      </Page>

      {/* One page per attached image proof */}
      {data.images.map((img, i) => (
        <Page key={i} size="A4" style={styles.page}>
          <Text style={styles.bold}>{img.caption}</Text>
          {/* eslint-disable-next-line jsx-a11y/alt-text */}
          <Image
            style={styles.proofImage}
            src={{ data: img.data, format: img.format }}
          />
          <Text style={styles.footer} fixed>
            88Mate — Visa Evidence Pack — attachment {i + 1} of{" "}
            {data.images.length}
          </Text>
        </Page>
      ))}
    </Document>
  );
}
